set_property SRC_FILE_INFO {cfile:C:/Users/admin/Verilog_Ram/basic-fpga-projects/mux_2x1/mux_2x1.srcs/constrs_1/new/mux_2x1.xdc rfile:../../../mux_2x1.srcs/constrs_1/new/mux_2x1.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H14 [get_ports I0]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H18 [get_ports I1]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G18 [get_ports S]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E18 [get_ports Y]
