set_property PACKAGE_PIN H14 [get_ports a]
set_property PACKAGE_PIN H18 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports c]
set_property IOSTANDARD LVCMOS33 [get_ports s]
set_property PACKAGE_PIN E18 [get_ports c]
set_property PACKAGE_PIN F13 [get_ports s]
